# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "argo-landing"
  tags:
  - "internal"
spec:
  type: "website"
  lifecycle: "production"
  owner: "skip"
  system: "skip"
